package app.project.sinsin.project.dao;

import java.util.ArrayList;

import app.project.sinsin.project.model.BaiViet;

/**
 * Created by nhan-dev on 6/4/2017.
 */

public class BaiVietDAO {
    public ArrayList<BaiViet> listBaiViet;

    public BaiVietDAO() {
        listBaiViet = new ArrayList<>();
        createDatabase();
    }

    public void createDatabase() {
        listBaiViet.add(new BaiViet(1, "Bai Viet 01", "<!doctype html>\n" +
                "<html>\n" +
                "<head>\n" +
                "\t<title>Bai viet 01 </title>\n" +
                "    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n" +
                "<body>\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><strong style=\"box-sizing: border-box; margin: 0px; padding: 0px; outline: none !important;\">1/ Sự ph&aacute;t triển của thai kỳ th&aacute;ng thứ 1</strong></p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-1\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 1\">Tuần 1</a>:&nbsp;Ở thời điểm n&agrave;y, b&eacute; y&ecirc;u của bạn l&agrave; một b&uacute;i nhỏ c&aacute;c tế b&agrave;o, được gọi l&agrave; t&uacute;i ph&ocirc;i, chứa một khối tế b&agrave;o b&ecirc;n trong sẽ ph&aacute;t triển th&agrave;nh ph&ocirc;i thai, một khoang chứa chất lỏng trở th&agrave;nh t&uacute;i nước ối. Khối tế b&agrave;o b&ecirc;n ngo&agrave;i sẽ h&igrave;nh th&agrave;nh nhau thai, mang oxy duy tr&igrave; sự sống, chất dinh dưỡng cho b&eacute; v&agrave; lấy đi c&aacute;c chất thải.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-2\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 2\">Tuần 2</a>:&nbsp;L&uacute;c n&agrave;y, b&eacute; chỉ l&agrave; một quả cầu t&iacute; hon gồm v&agrave;i trăm tế b&agrave;o đang nh&acirc;n l&ecirc;n nhanh ch&oacute;ng. Khi khối tế b&agrave;o n&agrave;y (gọi l&agrave; t&uacute;i ph&ocirc;i) đ&atilde; cư tr&uacute; trong tử cung của bạn, phần sẽ ph&aacute;t triển th&agrave;nh nhau thai bắt đầu sản xuất c&aacute;c hormone thai kỳ HCG (human chorionic gonadotropin), b&aacute;o hiệu cho buồng trứng ngừng sản sinh trứng v&agrave; tăng sự tiết hormone estrogen v&agrave; progesterone, giữ tử cung của bạn kh&ocirc;ng loại bỏ lớp nội mạc v&agrave; cư d&acirc;n nhỏ b&eacute; của m&igrave;nh đồng thời k&iacute;ch th&iacute;ch tăng trưởng nhau thai.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-3\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 3\">Tuần 3</a>: Tuần n&agrave;y đ&aacute;nh dấu sự bắt đầu của thai kỳ. Từ nay cho đến 10 tuần tuổi, tất cả c&aacute;c cơ quan trong cơ thể b&eacute; bắt đầu ph&aacute;t triển v&agrave; một số bắt đầu hoạt động. V&igrave; vậy, b&eacute; dễ bị tổn thương với bất cứ sự can thiệp v&agrave;o qu&aacute; tr&igrave;nh ph&aacute;t triển của b&eacute; trong giai đoạn n&agrave;y. Ngay b&acirc;y giờ b&eacute; l&agrave; một ph&ocirc;i thai nhỏ b&eacute;, bao gồm hai lớp: nội b&igrave; v&agrave; biểu b&igrave;, từ đ&oacute; tất cả c&aacute;c cơ quan v&agrave; bộ phận cơ thể của b&eacute; sẽ ph&aacute;t triển.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-4\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 4\">Tuần 4</a>:&nbsp;S&acirc;u trong tử cung, ph&ocirc;i thai đang tăng trưởng m&atilde;nh liệt. Tại thời điểm n&agrave;y, b&eacute; c&oacute; k&iacute;ch thước của một hạt m&egrave; v&agrave; tr&ocirc;ng giống như một con n&ograve;ng nọc nhỏ hơn một con người, gồm c&oacute; ba lớp: ngoại b&igrave;, trung b&igrave; v&agrave; nội b&igrave;, để h&igrave;nh th&agrave;nh tất cả c&aacute;c cơ quan v&agrave; m&ocirc; cho cơ thể b&eacute; sau n&agrave;y.</p>\n" +
                "</body>\n" +
                "</html>\n"));

        listBaiViet.add(new BaiViet(2, "Bai Viet 02", "<!doctype html>\n" +
                "<html>\n" +
                "<head>\n" +
                "\t<title>HTML Editor - Full Version</title>\n" +
                "    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n" +
                "</head>\n" +
                "<body>\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><strong style=\"box-sizing: border-box; margin: 0px; padding: 0px; outline: none !important;\">Sự ph&aacute;t triển của thai kỳ th&aacute;ng thứ 2</strong></p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-5\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 5\">Tuần 5</a>:&nbsp;Sự ph&aacute;t triển ch&iacute;nh của tuần n&agrave;y l&agrave; mũi, miệng v&agrave; tai. Một c&aacute;i đầu qu&aacute; khổ v&agrave; những đốm sẫm m&agrave;u nơi mắt v&agrave; lỗ mũi của b&eacute; bắt đầu h&igrave;nh th&agrave;nh. Tai của b&eacute; được đ&aacute;nh dấu bằng chỗ l&otilde;m nhỏ ở hai b&ecirc;n đầu v&agrave; tay ch&acirc;n b&eacute; như những chồi non đang nh&uacute; ra. Tim b&eacute; đập khoảng 100 đến 160 lần một ph&uacute;t, gần gấp đ&ocirc;i nhịp tim người lớn, v&agrave; m&aacute;u bắt đầu lưu th&ocirc;ng khắp cơ thể b&eacute;. Ruột cũng đang ph&aacute;t triển v&agrave; c&aacute;c chồi m&ocirc; h&igrave;nh th&agrave;nh phổi đ&atilde; xuất hiện. Tuyến y&ecirc;n cũng như phần c&ograve;n lại của bộ n&atilde;o, cơ bắp v&agrave; xương đang h&igrave;nh th&agrave;nh. L&uacute;c n&agrave;y, b&eacute; c&oacute; k&iacute;ch thước của một hạt đậu nhỏ.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-6\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 6\">Tuần 6</a>:&nbsp;Trong tuần n&agrave;y, b&agrave;n tay v&agrave; b&agrave;n ch&acirc;n b&eacute; đang nh&ocirc; ra từ c&aacute;nh tay v&agrave; ch&acirc;n, tr&ocirc;ng kh&aacute; giống những m&aacute;i ch&egrave;o. Thật ra, b&eacute; vẫn chỉ được coi l&agrave; một ph&ocirc;i thai v&agrave; c&ograve;n dấu t&iacute;ch của một c&aacute;i đu&ocirc;i nhỏ, l&agrave; phần nối d&agrave;i của xương cụt. C&aacute;i đu&ocirc;i sẽ biến mất trong v&agrave;i tuần v&agrave; đ&oacute; l&agrave; phần duy nhất sẽ nhỏ lại. B&eacute; đ&atilde; tăng gấp đ&ocirc;i k&iacute;ch thước kể từ tuần trước v&agrave; d&agrave;i hơn 1cm, gần bằng k&iacute;ch thước của một tr&aacute;i nho.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-7\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 7\">Tuần 7</a>:&nbsp;Bắt đầu xuất hiện những ng&oacute;n ch&acirc;n v&agrave; tay c&oacute; m&agrave;ng ph&aacute;t triển từ b&agrave;n tay v&agrave; b&agrave;n ch&acirc;n của b&eacute;. B&eacute; c&oacute; m&iacute; mắt, ống thở k&eacute;o d&agrave;i từ cổ họng đến c&aacute;c nh&aacute;nh của phổi đang ph&aacute;t triển v&agrave; &ldquo;đu&ocirc;i&rdquo; của b&eacute; dần biến mất. C&aacute;c tế b&agrave;o thần kinh đang ph&acirc;n nh&aacute;nh ra để kết nối với nhau, tạo th&agrave;nh hệ thần kinh sơ khai. Bộ phận sinh dục của b&eacute; vẫn chưa ph&aacute;t triển đầy đủ để bộc lộ giới t&iacute;nh l&agrave; trai hay g&aacute;i. B&eacute; c&oacute; k&iacute;ch thước của một hạt đậu ngự v&agrave; đang li&ecirc;n tục ph&aacute;t triển v&agrave; thay đổi, mặc d&ugrave; bạn vẫn chưa cảm nhận được.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-8\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 8\">Tuần 8</a>:&nbsp;Th&agrave;nh vi&ecirc;n mới của gia đ&igrave;nh đ&atilde; d&agrave;i khoảng 2,5cm, cỡ một quả nho Mỹ v&agrave; nặng chỉ v&agrave;i gram. H&igrave;nh h&agrave;i của b&eacute; ph&aacute;t triển đầy đủ hơn. C&aacute;c chi của cơ thể đ&atilde; h&igrave;nh th&agrave;nh đủ, nhưng cần trải qua nhiều giai đoạn để ho&agrave;n thiện trong những th&aacute;ng tiếp theo. Những ph&aacute;t triển trong tuần n&agrave;y: tim đ&atilde; ho&agrave;n th&agrave;nh việc ph&acirc;n chia th&agrave;nh bốn ngăn, v&agrave; c&aacute;c van tim bắt đầu h&igrave;nh th&agrave;nh. Phần đu&ocirc;i của ph&ocirc;i thai ho&agrave;n to&agrave;n biến mất. C&aacute;c cơ quan nội tạng, cơ bắp v&agrave; thần kinh đ&atilde; định h&igrave;nh. Cơ quan sinh dục đ&atilde; xuất hiện nhưng chưa thể ph&acirc;n biệt được giới t&iacute;nh của b&eacute; trong v&agrave;i tuần tới. Đ&ocirc;i mắt của b&eacute; đ&atilde; h&igrave;nh th&agrave;nh đầy đủ nhưng m&iacute; mắt vẫn đ&oacute;ng chặt cho đến 27 tuần tuổi. B&eacute; c&oacute; d&aacute;i tai nhỏ v&agrave; miệng, mũi, lỗ mũi định h&igrave;nh r&otilde; hơn. Nhau thai đ&atilde; ph&aacute;t triển đầy đủ để đảm nhận chức năng quan trọng l&agrave; sản sinh hormone. Sinh l&yacute; cơ bản của b&eacute; đ&atilde; sẵn s&agrave;ng v&agrave; b&eacute; sẽ tăng c&acirc;n nhanh ch&oacute;ng.</p>\n" +
                "</body>\n" +
                "</html>\n"));

        listBaiViet.add(new BaiViet(3, "Bai Viet 03", "<!doctype html>\n" +
                "<html>\n" +
                "<head>\n" +
                "\t<title>Bai viet 03 </title>\n" +
                "    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n" +

                "<body>\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><strong style=\"box-sizing: border-box; margin: 0px; padding: 0px; outline: none !important;\">1/ Sự ph&aacute;t triển của thai kỳ th&aacute;ng thứ 1</strong></p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-1\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 1\">Tuần 1</a>:&nbsp;Ở thời điểm n&agrave;y, b&eacute; y&ecirc;u của bạn l&agrave; một b&uacute;i nhỏ c&aacute;c tế b&agrave;o, được gọi l&agrave; t&uacute;i ph&ocirc;i, chứa một khối tế b&agrave;o b&ecirc;n trong sẽ ph&aacute;t triển th&agrave;nh ph&ocirc;i thai, một khoang chứa chất lỏng trở th&agrave;nh t&uacute;i nước ối. Khối tế b&agrave;o b&ecirc;n ngo&agrave;i sẽ h&igrave;nh th&agrave;nh nhau thai, mang oxy duy tr&igrave; sự sống, chất dinh dưỡng cho b&eacute; v&agrave; lấy đi c&aacute;c chất thải.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-2\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 2\">Tuần 2</a>:&nbsp;L&uacute;c n&agrave;y, b&eacute; chỉ l&agrave; một quả cầu t&iacute; hon gồm v&agrave;i trăm tế b&agrave;o đang nh&acirc;n l&ecirc;n nhanh ch&oacute;ng. Khi khối tế b&agrave;o n&agrave;y (gọi l&agrave; t&uacute;i ph&ocirc;i) đ&atilde; cư tr&uacute; trong tử cung của bạn, phần sẽ ph&aacute;t triển th&agrave;nh nhau thai bắt đầu sản xuất c&aacute;c hormone thai kỳ HCG (human chorionic gonadotropin), b&aacute;o hiệu cho buồng trứng ngừng sản sinh trứng v&agrave; tăng sự tiết hormone estrogen v&agrave; progesterone, giữ tử cung của bạn kh&ocirc;ng loại bỏ lớp nội mạc v&agrave; cư d&acirc;n nhỏ b&eacute; của m&igrave;nh đồng thời k&iacute;ch th&iacute;ch tăng trưởng nhau thai.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-3\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 3\">Tuần 3</a>: Tuần n&agrave;y đ&aacute;nh dấu sự bắt đầu của thai kỳ. Từ nay cho đến 10 tuần tuổi, tất cả c&aacute;c cơ quan trong cơ thể b&eacute; bắt đầu ph&aacute;t triển v&agrave; một số bắt đầu hoạt động. V&igrave; vậy, b&eacute; dễ bị tổn thương với bất cứ sự can thiệp v&agrave;o qu&aacute; tr&igrave;nh ph&aacute;t triển của b&eacute; trong giai đoạn n&agrave;y. Ngay b&acirc;y giờ b&eacute; l&agrave; một ph&ocirc;i thai nhỏ b&eacute;, bao gồm hai lớp: nội b&igrave; v&agrave; biểu b&igrave;, từ đ&oacute; tất cả c&aacute;c cơ quan v&agrave; bộ phận cơ thể của b&eacute; sẽ ph&aacute;t triển.</p>\n" +
                "\n" +
                "<p style=\"box-sizing: border-box; margin: 0px; padding: 15px 0px 0px; color: rgb(54, 54, 54); font-family: Arial; font-size: 14px; background-color: rgb(255, 255, 255); outline: none !important;\"><a href=\"http://www.marrybaby.vn/40-tuan-thai/su-phat-trien-cua-thai-ky-tuan-thai-thu-4\" style=\"box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 173, 219); text-decoration-line: none; outline: none !important;\" target=\"_blank\" title=\"Sự phát triển của thai kỳ: tuần thứ 4\">Tuần 4</a>:&nbsp;S&acirc;u trong tử cung, ph&ocirc;i thai đang tăng trưởng m&atilde;nh liệt. Tại thời điểm n&agrave;y, b&eacute; c&oacute; k&iacute;ch thước của một hạt m&egrave; v&agrave; tr&ocirc;ng giống như một con n&ograve;ng nọc nhỏ hơn một con người, gồm c&oacute; ba lớp: ngoại b&igrave;, trung b&igrave; v&agrave; nội b&igrave;, để h&igrave;nh th&agrave;nh tất cả c&aacute;c cơ quan v&agrave; m&ocirc; cho cơ thể b&eacute; sau n&agrave;y.</p>\n" +
                "</body>\n" +
                "</html>\n"));
    }
}
